### ISSUE TITLE
IComponent#toString arguments

### ISSUE THREAD

**Issue by Misiur** [fponticelli/edge#20]
Hello! Is there any reason why `IComponent#toString` requires arguments? Or is it accidental copy'n'paste from `injectConstructor`?

Defined here: https://github.com/fponticelli/edge/blob/8d46e43e98623d07953d2e57bb7470686ba91847/src/edge/core/macro/BuildComponent.hx#L37

**Comment by fponticelli** [comment]
No good reason!
