### ISSUE TITLE
Millions of allocations?

### ISSUE THREAD

**Issue by Misiur** [fponticelli/edge#24]
I tried to profile my project using hxscout, and I saw some worrying results. I reproduced it in small repo: https://github.com/Misiur/Alloc/blob/402a0344d8577113fad40df7fc0bc301b78006ee/Source/Main.hx

![](https://i.imgur.com/OEoAhuJ.png)

After just a few frames things get messy. For 1000 entities iterators generate 800000 allocations (last frame only has 550000)

![](https://i.imgur.com/cvhAFFY.png)

I'm not even sure how to debug that. Should I be worried? Or is it normal?

I wanted more frames, but app stops responding after that frame.

![](https://i.imgur.com/Tz5MY3b.png)
(Self time on left, total on right)

( https://github.com/fponticelli/edge/blob/1bc58741833f54a86f124dd0ae12466fc1919124/src/edge/View.hx#L11 :smiley: )

**Comment by fponticelli** [comment]
Using an iterator in `View` (particularly one that uses an anonymous object) is certainly not the best way to go speed wise. That most definitely requires a refactoring.

**Comment by fponticelli** [comment]
I tried some optimizations and fixes on this branch: https://github.com/fponticelli/edge/tree/kedge
Would you mind testing?

**Comment by Misiur** [comment]
Nice, for 4k tiles went from 8FPS to 45FPS on CPP target! Thank you.

**Comment by fponticelli** [comment]
That's cool. I think we can do better :) ... Views in general need a better and more flexible implementation.

**Comment by RblSb** [comment]
@fponticelli in the kedge branch there is a bug - with code `class Some implements IComponent {}` (without vars/constructor) the compiler produces errors like `Missing ;` and `Main.hx:5: lines 5-15 : Defined in this class`.
